# Generated by Django 3.1.11 on 2022-07-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220727_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='descriptipn',
            new_name='description',
        ),
    ]
